name: Android CI

on:
  push:
    branches: [main]
jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      # - name: Setup Node.js
      #   uses: actions/setup-node@v6
      #   with:
      #     node-version: latest

      # - name: Setup Java 17
      #   uses: actions/setup-java@v5
      #   with:
      #     distribution: temurin
      #     java-version: 17

      # - name: Install dependencies
      #   run: |
      #     npm install
      #     cd android && chmod +x gradlew && cd ..

      - name: Base64 encoded Keystore
        run: |
          if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "âŒ KEYSTORE_BASE64 secret is missing!"
            exit 1
          else
            echo "âœ… KEYSTORE_BASE64 secret found."
          fi
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-key.keystore

      # - name: ğŸ—ï¸ Build Release APK
      #   run: |
      #     cd android
      #     ./gradlew assembleRelease

      # - name: Upload APK artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release
      #     path: android/app/build/outputs/apk/release/app-release.apk

      # - name: Build Success
      #   run: echo "Android build successfully"
